version: '3'

services:
  api:
    build: api
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PASS=stutter123
      - DB_NAME=postgres
      - SECRET_KEY=stutter123
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=stutter123
  web:
    build: web
    ports:
      - 3000:3000
    volumes:
      - ./web/public:/app/public
      - ./web/src:/app/src
    depends_on:
      - api